// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5_H8MR4ujXiRrTGOQEooR69UXM8295A',
    appId: '1:506588318374:web:a22055dfc7a52570718267',
    messagingSenderId: '506588318374',
    projectId: 'loglife-24920',
    authDomain: 'loglife-24920.firebaseapp.com',
    storageBucket: 'loglife-24920.appspot.com',
    measurementId: 'G-ZVYLHF58ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVgN3f0b0qjxBgpU949y7-NA1Noj2M3f4',
    appId: '1:506588318374:android:3c894f0944d7dbde718267',
    messagingSenderId: '506588318374',
    projectId: 'loglife-24920',
    storageBucket: 'loglife-24920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcJoL6myqwO4QaokNp2QrUc_1RCkz77P0',
    appId: '1:506588318374:ios:3ecde54e46119f0a718267',
    messagingSenderId: '506588318374',
    projectId: 'loglife-24920',
    storageBucket: 'loglife-24920.appspot.com',
    iosBundleId: 'com.example.loglife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcJoL6myqwO4QaokNp2QrUc_1RCkz77P0',
    appId: '1:506588318374:ios:3ecde54e46119f0a718267',
    messagingSenderId: '506588318374',
    projectId: 'loglife-24920',
    storageBucket: 'loglife-24920.appspot.com',
    iosBundleId: 'com.example.loglife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL5_H8MR4ujXiRrTGOQEooR69UXM8295A',
    appId: '1:506588318374:web:f20fb9e786f64cf5718267',
    messagingSenderId: '506588318374',
    projectId: 'loglife-24920',
    authDomain: 'loglife-24920.firebaseapp.com',
    storageBucket: 'loglife-24920.appspot.com',
    measurementId: 'G-66G8H1R2RD',
  );
}
